const x = {
    exception_code: null,
    matches: [
        {
            'create-date': '2024-07-10 06:16:53',
            'created-by': 'MateCat',
            id: '425833062427673780',
            'last-update-date': '2024-07-10 06:16:53',
            'last-updated-by': 'MateCat',
            match: 1,
            penalty: 0,
            quality: '74',
            reference: null,
            segment: 'Hello',
            source: 'en-GB',
            subject: 'All',
            target: 'bn-IN',
            translation: 'হ্যালো',
            'usage-count': 18,
        },
        {
            'create-date': '2023-05-20 03:28:18',
            'created-by': 'Public Web',
            id: '425833062427119295',
            'last-update-date': '2023-05-20 03:28:18',
            'last-updated-by': 'Public Web',
            match: 0.99,
            penalty: 0,
            quality: 74,
            reference: null,
            segment: 'Hello',
            source: 'en-GB',
            subject: null,
            target: 'bn-IN',
            translation: '',
            'usage-count': 2,
        },
        {
            'create-date': '2022-12-03 18:43:48',
            'created-by': 'MateCat',
            id: '427962602',
            'last-update-date': '2022-12-03 18:43:48',
            'last-updated-by': '',
            match: 0.99,
            penalty: 0,
            quality: '100',
            reference: null,
            segment: 'Hello',
            source: 'en-US',
            subject: '',
            target: 'bn-IN',
            translation: 'ছবি ভেজো আপাকি',
            'usage-count': 4,
        },
    ],
    mtLangSupported: null,
    quotaFinished: false,
    responderId: null,
    responseData: { match: 1, translatedText: 'হ্যালো' },
    responseDetails: '',
    responseStatus: 200,
};
